# Generated by Django 6.0.2 on 2026-02-06 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'модель ведущего моста',
                'verbose_name_plural': 'модели ведущих мостов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'модель двигателя',
                'verbose_name_plural': 'модели двигателей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'модель техники',
                'verbose_name_plural': 'модели техники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SteerAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'модель управляемого моста',
                'verbose_name_plural': 'модели управляемых мостов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'модель трансмиссии',
                'verbose_name_plural': 'модели трансмиссий',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='зав. № машины')),
                ('engine_serial', models.CharField(blank=True, max_length=100, verbose_name='зав. № двигателя')),
                ('transmission_serial', models.CharField(blank=True, max_length=100, verbose_name='зав. № трансмиссии')),
                ('drive_axle_serial', models.CharField(blank=True, max_length=100, verbose_name='зав. № ведущего моста')),
                ('steer_axle_serial', models.CharField(blank=True, max_length=100, verbose_name='зав. № управляемого моста')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='договор поставки №')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='дата договора')),
                ('shipment_date', models.DateField(blank=True, null=True, verbose_name='дата отгрузки с завода')),
                ('consignee', models.CharField(blank=True, max_length=300, verbose_name='грузополучатель (конечный потребитель)')),
                ('operation_address', models.CharField(blank=True, max_length=500, verbose_name='адрес поставки / эксплуатации')),
                ('options', models.TextField(blank=True, verbose_name='комплектация / доп. опции')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_machines', to=settings.AUTH_USER_MODEL, verbose_name='клиент')),
                ('drive_axle_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='core.driveaxlemodel', verbose_name='модель ведущего моста')),
                ('engine_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='core.enginemodel', verbose_name='модель двигателя')),
                ('service_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_machines', to=settings.AUTH_USER_MODEL, verbose_name='сервисная компания')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='core.machinemodel', verbose_name='модель техники')),
                ('steer_axle_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='core.steeraxlemodel', verbose_name='модель управляемого моста')),
                ('transmission_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='core.transmissionmodel', verbose_name='модель трансмиссии')),
            ],
            options={
                'verbose_name': 'машина',
                'verbose_name_plural': 'машины',
                'ordering': ['-shipment_date', 'serial_number'],
                'indexes': [models.Index(fields=['serial_number'], name='core_machin_serial__3754e9_idx'), models.Index(fields=['shipment_date'], name='core_machin_shipmen_f39392_idx')],
            },
        ),
    ]
