# Generated by Django 6.0.2 on 2026-02-08 06:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_driveaxlemodel_enginemodel_machinemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'узел отказа',
                'verbose_name_plural': 'узлы отказа',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'вид ТО',
                'verbose_name_plural': 'виды ТО',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'способ восстановления',
                'verbose_name_plural': 'способы восстановления',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='machine',
            name='serial_number',
            field=models.CharField(db_index=True, help_text='Только латинские буквы, цифры, -, _', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_serial', message='Заводской номер может содержать только латинские буквы, цифры, дефис и подчёркивание.', regex='^[A-Za-z0-9\\-_]+$')], verbose_name='зав. № машины'),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата проведения ТО')),
                ('hours', models.IntegerField(default=0, verbose_name='наработка, м/час')),
                ('order_number', models.CharField(blank=True, max_length=100, verbose_name='№ заказ-наряда')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='дата заказ-наряда')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='core.machine', verbose_name='машина')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_maintenances', to=settings.AUTH_USER_MODEL, verbose_name='организация, проводившая ТО')),
                ('service_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_maintenances', to=settings.AUTH_USER_MODEL, verbose_name='сервисная компания')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenances', to='core.maintenancetype', verbose_name='вид ТО')),
            ],
            options={
                'verbose_name': 'ТО',
                'verbose_name_plural': 'ТО',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField(verbose_name='дата отказа')),
                ('hours', models.IntegerField(default=0, verbose_name='наработка, м/час')),
                ('failure_description', models.TextField(blank=True, verbose_name='описание отказа')),
                ('parts_used', models.TextField(blank=True, verbose_name='используемые запасные части')),
                ('recovery_date', models.DateField(blank=True, null=True, verbose_name='дата восстановления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.machine', verbose_name='машина')),
                ('service_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_claims', to=settings.AUTH_USER_MODEL, verbose_name='сервисная компания')),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='core.failurenode', verbose_name='узел отказа')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='core.recoverymethod', verbose_name='способ восстановления')),
            ],
            options={
                'verbose_name': 'рекламация',
                'verbose_name_plural': 'рекламации',
                'ordering': ['-failure_date'],
            },
        ),
    ]
